site_name: Matthys' Portfolio
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthysvr/
    - icon: fontawesome/brands/github
      link: https://github.com/matthysvr
  analytics:
    provider: google
    property: G-807JJ3EX90

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

nav: 
  - Home: index.md
  - Undergrad: 
    - undergrad/index.md
    - File Monitor: undergrad/file-monitor.md
    - Graphical Linear Programming Solver: undergrad/graphical-solver.md
    - Natural Distribution Sim: undergrad/nds.md
    - Online Weather App: undergrad/online-weather-app.md
    - Plane Sim - Shortest Route: undergrad/plane-sim.md
    - SEN381 Project: undergrad/sen381-project.md
  - Postgrad: postgrad/index.md
  - Mini Projects / Ideas:
    - mini-projects/index.md
    - Python:
      - Conway Game of Life: mini-projects/cgl.md
    - C#:
      - Critical Path Calculator: mini-projects/critical-path-calculator.md
      - Website (WHOIS) Reporter: mini-projects/website-reporter.md
copyright: |
  &copy; 2023 <a href="https://www.matthysvr.com/" target="_blank" rel="noopener">Matthys van Rooyen</a>