site_name: Matthys' Portfolio
site_url: https://portfolio.matthysvr.com/
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthysvr/
    - icon: fontawesome/brands/github
      link: https://github.com/matthysvr
  analytics:
    provider: google
    property: G-807JJ3EX90

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
      show_input: True
      remove_tag_config:
        remove_input_tags:
          - hide_code
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

nav: 
  - Home: index.md
  - Undergrad: 
    - undergrad/index.md
    - File Monitor: undergrad/file-monitor.md
    - Graphical Linear Programming Solver: undergrad/graphical-solver.md
    - Natural Distribution Sim: undergrad/nds.md
    - Online Weather App: undergrad/online-weather-app.md
    - Plane Sim - Shortest Route: undergrad/plane-sim.md
    - SEN381 Project: undergrad/sen381-project.md
  - Postgrad: 
    - postgrad/index.md
    - Data Programming in Python:
      - Coursework 1:  postgrad/Data Programming in Python/CW1.ipynb
      - Coursework 2:  postgrad/Data Programming in Python/CW2.ipynb
    - Machine Learning:
      - Coursework 1:  postgrad/Machine Learning/CW1.ipynb
      - Coursework 2:  postgrad/Machine Learning/CW2.ipynb
    - Statistics and Statistical Data Mining:
      - Coursework:  postgrad/Statistics and Statistical Data Mining/CW1.ipynb
    - Mathematics for Data Science:
      - Coursework: postgrad/Mathematics for Data Science/CW1.md
    - Artificial Intelligence:
      - Coursework: postgrad/Artificial Intelligence/Coursework.md
    - Neural Networks:
      - Coursework 1: postgrad/Neural Networks/CW1.ipynb
      - Coursework 2: postgrad/Neural Networks/CW2.ipynb
    - Natural Language Processing:
      - Coursework: postgrad/Natural Language Processing/CW1.ipynb
    - Social Media and Network Science:
      - Social Media Coursework 1: postgrad/Social Media and Network Science/Social Media Coursework 1.md
      - Network Science Coursework 1: postgrad/Social Media and Network Science/Network Science Coursework 1.md
      - Social Media and Network Science Coursework 2: postgrad/Social Media and Network Science/Social Media and Network Science Coursework 2.md
    - Data Science Research Topics:
      - Literature Review: postgrad/Data Science Research Topics/Literature Review.md
      - Research Project Proposal: postgrad/Data Science Research Topics/Research Project Proposal.md
    - Big Data Analysis:
      - Coursework 1: postgrad/Big Data Analysis/CW1.ipynb
  - Mini Projects / Ideas:
    - mini-projects/index.md
    - Python:
      - Conway Game of Life: mini-projects/cgl.md
    - C#:
      - Critical Path Calculator: mini-projects/critical-path-calculator.md
      - Website (WHOIS) Reporter: mini-projects/website-reporter.md
    - Rust:
      - Machine Learning Library: mini-projects/rust_ml.md

copyright: |
  &copy; 2023 - 2024 <a href="https://www.matthysvr.com/" target="_blank" rel="noopener">Matthys van Rooyen</a>